[user]
name = ''
initials = ''

address = ''
full_address = ''

institution = ''

email = ''
website = ''
grant = ''

[github]
username = ''
email = ''

[render]
clean_whitespace = false
bibinfo_file = 'bibinfo'
classinfo_file = 'classinfo'

# the root of the .tex file in the the working directory
default_tex_name = 'main'

# other config files at the root
project_macro_file = 'project-macros'
project_data_folder = '.texproject'

# text subsituted for fields which require user input
replace_text = 'REPLACE'

# options given to arxiv autotex
arxiv_autotex = []

[metadata]
# additional metadata used by templates

[process]

# extra options to pass to latexmk
latexmk_compile_options = []

# files to ignore when exporting source files, and in .gitignore
ignore_patterns = [
    '*.aux',
    '*.bak',
    '*.bbl',
    '*.bcf',
    '*.blg',
    '*.brf',
    '*.dvi',
    '*.fdb_latexmk',
    '*.fls',
    '*.latexmain',
    '*.log',
    '*.mtc',
    '*.out',
    '*.pdf',
    '*.pgs',
    '*.run.xml',
    '*.snm',
    '*.svg',
    '*.synctex.gz*',
    '*.synctex(busy)',
    '*.tar*',
    '*.thm',
    '*.toc',
    '*.zip',
    '.DS_Store',
    '.git',
    'archive*',
    'tmp'
]
